// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.example.cs217b.ndn_hangman;

public final class MessageBuffer {
  private MessageBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessagesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.cs217b.ndn_hangman.Messages)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required .com.example.cs217b.ndn_hangman.Messages.MessageType type = 2 [default = GUESS];</code>
     */
    boolean hasType();
    /**
     * <code>required .com.example.cs217b.ndn_hangman.Messages.MessageType type = 2 [default = GUESS];</code>
     */
    com.example.cs217b.ndn_hangman.MessageBuffer.Messages.MessageType getType();

    /**
     * <code>optional string word = 3;</code>
     */
    boolean hasWord();
    /**
     * <code>optional string word = 3;</code>
     */
    java.lang.String getWord();
    /**
     * <code>optional string word = 3;</code>
     */
    com.google.protobuf.ByteString
        getWordBytes();

    /**
     * <code>required int32 timestamp = 4;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int32 timestamp = 4;</code>
     */
    int getTimestamp();
  }
  /**
   * Protobuf type {@code com.example.cs217b.ndn_hangman.Messages}
   */
  public static final class Messages extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.example.cs217b.ndn_hangman.Messages)
      MessagesOrBuilder {
    // Use Messages.newBuilder() to construct.
    private Messages(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Messages(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Messages defaultInstance;
    public static Messages getDefaultInstance() {
      return defaultInstance;
    }

    public Messages getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Messages(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.example.cs217b.ndn_hangman.MessageBuffer.Messages.MessageType value = com.example.cs217b.ndn_hangman.MessageBuffer.Messages.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              word_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timestamp_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.cs217b.ndn_hangman.MessageBuffer.internal_static_com_example_cs217b_ndn_hangman_Messages_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.cs217b.ndn_hangman.MessageBuffer.internal_static_com_example_cs217b_ndn_hangman_Messages_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.cs217b.ndn_hangman.MessageBuffer.Messages.class, com.example.cs217b.ndn_hangman.MessageBuffer.Messages.Builder.class);
    }

    public static com.google.protobuf.Parser<Messages> PARSER =
        new com.google.protobuf.AbstractParser<Messages>() {
      public Messages parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Messages(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Messages> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.example.cs217b.ndn_hangman.Messages.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GUESS = 0;</code>
       */
      GUESS(0, 0),
      /**
       * <code>EVAL = 1;</code>
       */
      EVAL(1, 1),
      /**
       * <code>JOIN = 2;</code>
       */
      JOIN(2, 2),
      /**
       * <code>LEAVE = 3;</code>
       */
      LEAVE(3, 3),
      /**
       * <code>HELLO = 4;</code>
       */
      HELLO(4, 4),
      /**
       * <code>OTHER = 5;</code>
       */
      OTHER(5, 5),
      ;

      /**
       * <code>GUESS = 0;</code>
       */
      public static final int GUESS_VALUE = 0;
      /**
       * <code>EVAL = 1;</code>
       */
      public static final int EVAL_VALUE = 1;
      /**
       * <code>JOIN = 2;</code>
       */
      public static final int JOIN_VALUE = 2;
      /**
       * <code>LEAVE = 3;</code>
       */
      public static final int LEAVE_VALUE = 3;
      /**
       * <code>HELLO = 4;</code>
       */
      public static final int HELLO_VALUE = 4;
      /**
       * <code>OTHER = 5;</code>
       */
      public static final int OTHER_VALUE = 5;


      public final int getNumber() { return value; }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return GUESS;
          case 1: return EVAL;
          case 2: return JOIN;
          case 3: return LEAVE;
          case 4: return HELLO;
          case 5: return OTHER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.example.cs217b.ndn_hangman.MessageBuffer.Messages.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.example.cs217b.ndn_hangman.Messages.MessageType)
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private com.example.cs217b.ndn_hangman.MessageBuffer.Messages.MessageType type_;
    /**
     * <code>required .com.example.cs217b.ndn_hangman.Messages.MessageType type = 2 [default = GUESS];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.example.cs217b.ndn_hangman.Messages.MessageType type = 2 [default = GUESS];</code>
     */
    public com.example.cs217b.ndn_hangman.MessageBuffer.Messages.MessageType getType() {
      return type_;
    }

    public static final int WORD_FIELD_NUMBER = 3;
    private java.lang.Object word_;
    /**
     * <code>optional string word = 3;</code>
     */
    public boolean hasWord() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string word = 3;</code>
     */
    public java.lang.String getWord() {
      java.lang.Object ref = word_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          word_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string word = 3;</code>
     */
    public com.google.protobuf.ByteString
        getWordBytes() {
      java.lang.Object ref = word_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        word_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private int timestamp_;
    /**
     * <code>required int32 timestamp = 4;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 timestamp = 4;</code>
     */
    public int getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      name_ = "";
      type_ = com.example.cs217b.ndn_hangman.MessageBuffer.Messages.MessageType.GUESS;
      word_ = "";
      timestamp_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getWordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getWordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.cs217b.ndn_hangman.MessageBuffer.Messages parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.cs217b.ndn_hangman.MessageBuffer.Messages parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.cs217b.ndn_hangman.MessageBuffer.Messages parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.cs217b.ndn_hangman.MessageBuffer.Messages parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.cs217b.ndn_hangman.MessageBuffer.Messages parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.cs217b.ndn_hangman.MessageBuffer.Messages parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.cs217b.ndn_hangman.MessageBuffer.Messages parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.cs217b.ndn_hangman.MessageBuffer.Messages parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.cs217b.ndn_hangman.MessageBuffer.Messages parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.cs217b.ndn_hangman.MessageBuffer.Messages parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.cs217b.ndn_hangman.MessageBuffer.Messages prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.cs217b.ndn_hangman.Messages}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.cs217b.ndn_hangman.Messages)
        com.example.cs217b.ndn_hangman.MessageBuffer.MessagesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.cs217b.ndn_hangman.MessageBuffer.internal_static_com_example_cs217b_ndn_hangman_Messages_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.cs217b.ndn_hangman.MessageBuffer.internal_static_com_example_cs217b_ndn_hangman_Messages_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.cs217b.ndn_hangman.MessageBuffer.Messages.class, com.example.cs217b.ndn_hangman.MessageBuffer.Messages.Builder.class);
      }

      // Construct using com.example.cs217b.ndn_hangman.MessageBuffer.Messages.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.example.cs217b.ndn_hangman.MessageBuffer.Messages.MessageType.GUESS;
        bitField0_ = (bitField0_ & ~0x00000002);
        word_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.cs217b.ndn_hangman.MessageBuffer.internal_static_com_example_cs217b_ndn_hangman_Messages_descriptor;
      }

      public com.example.cs217b.ndn_hangman.MessageBuffer.Messages getDefaultInstanceForType() {
        return com.example.cs217b.ndn_hangman.MessageBuffer.Messages.getDefaultInstance();
      }

      public com.example.cs217b.ndn_hangman.MessageBuffer.Messages build() {
        com.example.cs217b.ndn_hangman.MessageBuffer.Messages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.cs217b.ndn_hangman.MessageBuffer.Messages buildPartial() {
        com.example.cs217b.ndn_hangman.MessageBuffer.Messages result = new com.example.cs217b.ndn_hangman.MessageBuffer.Messages(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.word_ = word_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.cs217b.ndn_hangman.MessageBuffer.Messages) {
          return mergeFrom((com.example.cs217b.ndn_hangman.MessageBuffer.Messages)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.cs217b.ndn_hangman.MessageBuffer.Messages other) {
        if (other == com.example.cs217b.ndn_hangman.MessageBuffer.Messages.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasWord()) {
          bitField0_ |= 0x00000004;
          word_ = other.word_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.cs217b.ndn_hangman.MessageBuffer.Messages parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.cs217b.ndn_hangman.MessageBuffer.Messages) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private com.example.cs217b.ndn_hangman.MessageBuffer.Messages.MessageType type_ = com.example.cs217b.ndn_hangman.MessageBuffer.Messages.MessageType.GUESS;
      /**
       * <code>required .com.example.cs217b.ndn_hangman.Messages.MessageType type = 2 [default = GUESS];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.example.cs217b.ndn_hangman.Messages.MessageType type = 2 [default = GUESS];</code>
       */
      public com.example.cs217b.ndn_hangman.MessageBuffer.Messages.MessageType getType() {
        return type_;
      }
      /**
       * <code>required .com.example.cs217b.ndn_hangman.Messages.MessageType type = 2 [default = GUESS];</code>
       */
      public Builder setType(com.example.cs217b.ndn_hangman.MessageBuffer.Messages.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.example.cs217b.ndn_hangman.Messages.MessageType type = 2 [default = GUESS];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = com.example.cs217b.ndn_hangman.MessageBuffer.Messages.MessageType.GUESS;
        onChanged();
        return this;
      }

      private java.lang.Object word_ = "";
      /**
       * <code>optional string word = 3;</code>
       */
      public boolean hasWord() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string word = 3;</code>
       */
      public java.lang.String getWord() {
        java.lang.Object ref = word_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            word_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string word = 3;</code>
       */
      public com.google.protobuf.ByteString
          getWordBytes() {
        java.lang.Object ref = word_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          word_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string word = 3;</code>
       */
      public Builder setWord(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        word_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string word = 3;</code>
       */
      public Builder clearWord() {
        bitField0_ = (bitField0_ & ~0x00000004);
        word_ = getDefaultInstance().getWord();
        onChanged();
        return this;
      }
      /**
       * <code>optional string word = 3;</code>
       */
      public Builder setWordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        word_ = value;
        onChanged();
        return this;
      }

      private int timestamp_ ;
      /**
       * <code>required int32 timestamp = 4;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 timestamp = 4;</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int32 timestamp = 4;</code>
       */
      public Builder setTimestamp(int value) {
        bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.cs217b.ndn_hangman.Messages)
    }

    static {
      defaultInstance = new Messages(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.example.cs217b.ndn_hangman.Messages)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_cs217b_ndn_hangman_Messages_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_cs217b_ndn_hangman_Messages_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\036com.example.cs217b.ndn" +
      "_hangman\"\323\001\n\010Messages\022\014\n\004name\030\001 \002(\t\022I\n\004t" +
      "ype\030\002 \002(\01624.com.example.cs217b.ndn_hangm" +
      "an.Messages.MessageType:\005GUESS\022\014\n\004word\030\003" +
      " \001(\t\022\021\n\ttimestamp\030\004 \002(\005\"M\n\013MessageType\022\t" +
      "\n\005GUESS\020\000\022\010\n\004EVAL\020\001\022\010\n\004JOIN\020\002\022\t\n\005LEAVE\020\003" +
      "\022\t\n\005HELLO\020\004\022\t\n\005OTHER\020\005B\017B\rMessageBuffer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_cs217b_ndn_hangman_Messages_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_cs217b_ndn_hangman_Messages_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_cs217b_ndn_hangman_Messages_descriptor,
        new java.lang.String[] { "Name", "Type", "Word", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
